# Generated by Django 4.2.3 on 2023-07-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OddsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_ns", models.IntegerField(default=-1)),
                ("book", models.CharField(max_length=200)),
                ("sport", models.CharField(max_length=200)),
                ("game_id", models.IntegerField(default=-1)),
                ("odds_description", models.CharField(max_length=200)),
                ("odds", models.IntegerField(default=-1)),
            ],
        ),
    ]
