# Generated by Django 4.2.3 on 2023-08-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odds", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oddsitem",
            old_name="odds_description",
            new_name="market_description",
        ),
        migrations.AddField(
            model_name="oddsitem",
            name="market_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="oddsitem",
            name="plays",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="oddsitem",
            name="odds",
            field=models.TextField(null=True),
        ),
    ]
