# Generated by Django 4.2.3 on 2023-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odds", "0002_rename_odds_description_oddsitem_market_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oddsitem",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="oddsitem",
            name="market_id",
        ),
        migrations.AddField(
            model_name="oddsitem",
            name="game_description",
            field=models.CharField(default="Unknown Game", max_length=200),
        ),
        migrations.AddField(
            model_name="oddsitem",
            name="source_url",
            field=models.CharField(default="Unknown URL", max_length=1024),
        ),
        migrations.AlterField(
            model_name="oddsitem",
            name="market_description",
            field=models.CharField(default="Unknown Market", max_length=200),
        ),
    ]
