# Generated by Django 4.2.3 on 2023-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odds", "0003_remove_oddsitem_game_id_remove_oddsitem_market_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oddsitem",
            name="game_description",
            field=models.CharField(default="unknown_game", max_length=200),
        ),
        migrations.AlterField(
            model_name="oddsitem",
            name="market_description",
            field=models.CharField(default="unknown_market", max_length=200),
        ),
    ]
