# Generated by Django 4.2.3 on 2023-08-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odds", "0004_alter_oddsitem_game_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oddsitem",
            name="source_url",
            field=models.CharField(default="unknown_url", max_length=1024),
        ),
    ]
